// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_assesment/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:convert' as _i15;
import 'dart:typed_data' as _i17;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_assesment/core/error/failure.dart' as _i6;
import 'package:flutter_assesment/features/home/data/data_sources/category_remote_data_source.dart'
    as _i8;
import 'package:flutter_assesment/features/home/data/data_sources/popular_remote_data_source.dart'
    as _i13;
import 'package:flutter_assesment/features/home/data/models/category_model.dart'
    as _i9;
import 'package:flutter_assesment/features/home/data/models/popular_model.dart'
    as _i14;
import 'package:flutter_assesment/features/home/domain/entities/category.dart'
    as _i7;
import 'package:flutter_assesment/features/home/domain/entities/popular.dart'
    as _i12;
import 'package:flutter_assesment/features/home/domain/repositories/category_repository.dart'
    as _i3;
import 'package:flutter_assesment/features/home/domain/repositories/popular_repository.dart'
    as _i11;
import 'package:flutter_assesment/features/home/domain/usecases/get_all_categories.dart'
    as _i10;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategoryRepository_1 extends _i1.SmartFake
    implements _i3.CategoryRepository {
  _FakeCategoryRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_2 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_3 extends _i1.SmartFake
    implements _i4.StreamedResponse {
  _FakeStreamedResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i3.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.CategoryEntity>>>
      getCategories() => (super.noSuchMethod(
            Invocation.method(
              #getCategories,
              [],
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.Failure, List<_i7.CategoryEntity>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.CategoryEntity>>(
              this,
              Invocation.method(
                #getCategories,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.CategoryEntity>>>);
}

/// A class which mocks [CategoryRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRemoteDataSource extends _i1.Mock
    implements _i8.CategoryRemoteDataSource {
  MockCategoryRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i9.CategoryModel>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue:
            _i5.Future<List<_i9.CategoryModel>>.value(<_i9.CategoryModel>[]),
      ) as _i5.Future<List<_i9.CategoryModel>>);
}

/// A class which mocks [GetAllCategoriesUserCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllCategoriesUserCase extends _i1.Mock
    implements _i10.GetAllCategoriesUserCase {
  MockGetAllCategoriesUserCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CategoryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCategoryRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.CategoryRepository);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.CategoryEntity>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, List<_i7.CategoryEntity>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.CategoryEntity>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.CategoryEntity>>>);
}

/// A class which mocks [PopularRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularRepository extends _i1.Mock implements _i11.PopularRepository {
  MockPopularRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i12.PopularEntity>>>
      getAllPopular() => (super.noSuchMethod(
            Invocation.method(
              #getAllPopular,
              [],
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.Failure, List<_i12.PopularEntity>>>.value(
                _FakeEither_0<_i6.Failure, List<_i12.PopularEntity>>(
              this,
              Invocation.method(
                #getAllPopular,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, List<_i12.PopularEntity>>>);
}

/// A class which mocks [PopularRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularRemoteDataSource extends _i1.Mock
    implements _i13.PopularRemoteDataSource {
  MockPopularRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i14.PopularModel>> getPopulars() => (super.noSuchMethod(
        Invocation.method(
          #getPopulars,
          [],
        ),
        returnValue:
            _i5.Future<List<_i14.PopularModel>>.value(<_i14.PopularModel>[]),
      ) as _i5.Future<List<_i14.PopularModel>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i4.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i4.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i15.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i15.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i15.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i4.Response>);

  @override
  _i5.Future<_i4.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i15.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i5.Future<_i4.Response>.value(_FakeResponse_2(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i5.Future<_i4.Response>);

  @override
  _i5.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<String>.value(_i16.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i17.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i5.Future<_i17.Uint8List>.value(_i17.Uint8List(0)),
      ) as _i5.Future<_i17.Uint8List>);

  @override
  _i5.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i5.Future<_i4.StreamedResponse>.value(_FakeStreamedResponse_3(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i5.Future<_i4.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
