// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_assesment/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:convert' as _i22;
import 'dart:typed_data' as _i24;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_assesment/config/local_database/hive_db_service.dart'
    as _i20;
import 'package:flutter_assesment/core/error/failure.dart' as _i9;
import 'package:flutter_assesment/features/home/data/data_sources/category_remote_data_source.dart'
    as _i11;
import 'package:flutter_assesment/features/home/data/data_sources/local/popular_local_data_source.dart'
    as _i21;
import 'package:flutter_assesment/features/home/data/data_sources/popular_remote_data_source.dart'
    as _i15;
import 'package:flutter_assesment/features/home/data/models/category_model.dart'
    as _i12;
import 'package:flutter_assesment/features/home/data/models/popular_model.dart'
    as _i16;
import 'package:flutter_assesment/features/home/domain/entities/category.dart'
    as _i10;
import 'package:flutter_assesment/features/home/domain/entities/popular.dart'
    as _i14;
import 'package:flutter_assesment/features/home/domain/repositories/category_repository.dart'
    as _i3;
import 'package:flutter_assesment/features/home/domain/repositories/popular_repository.dart'
    as _i4;
import 'package:flutter_assesment/features/home/domain/usecases/get_all_categories.dart'
    as _i13;
import 'package:flutter_assesment/features/home/domain/usecases/get_all_popular.dart'
    as _i17;
import 'package:flutter_assesment/features/tour/data/data-sources/tour_detail_data_source.dart'
    as _i18;
import 'package:flutter_assesment/features/tour/domain/entities/tour_detail_entity.dart'
    as _i5;
import 'package:flutter_assesment/features/tour/domain/repositories/tour_repository.dart'
    as _i6;
import 'package:flutter_assesment/features/tour/domain/usecases/get_tour_detail.dart'
    as _i19;
import 'package:http/http.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i23;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategoryRepository_1 extends _i1.SmartFake
    implements _i3.CategoryRepository {
  _FakeCategoryRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePopularRepository_2 extends _i1.SmartFake
    implements _i4.PopularRepository {
  _FakePopularRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTourDetailEntity_3 extends _i1.SmartFake
    implements _i5.TourDetailEntity {
  _FakeTourDetailEntity_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTourRepository_4 extends _i1.SmartFake
    implements _i6.TourRepository {
  _FakeTourRepository_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_5 extends _i1.SmartFake implements _i7.Response {
  _FakeResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_6 extends _i1.SmartFake
    implements _i7.StreamedResponse {
  _FakeStreamedResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i3.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.CategoryEntity>>>
      getCategories() => (super.noSuchMethod(
            Invocation.method(
              #getCategories,
              [],
            ),
            returnValue: _i8.Future<
                    _i2.Either<_i9.Failure, List<_i10.CategoryEntity>>>.value(
                _FakeEither_0<_i9.Failure, List<_i10.CategoryEntity>>(
              this,
              Invocation.method(
                #getCategories,
                [],
              ),
            )),
          ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.CategoryEntity>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.CategoryEntity>>> search(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
        ),
        returnValue: _i8
            .Future<_i2.Either<_i9.Failure, List<_i10.CategoryEntity>>>.value(
            _FakeEither_0<_i9.Failure, List<_i10.CategoryEntity>>(
          this,
          Invocation.method(
            #search,
            [query],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.CategoryEntity>>>);
}

/// A class which mocks [CategoryRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRemoteDataSource extends _i1.Mock
    implements _i11.CategoryRemoteDataSource {
  MockCategoryRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i12.CategoryModel>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue:
            _i8.Future<List<_i12.CategoryModel>>.value(<_i12.CategoryModel>[]),
      ) as _i8.Future<List<_i12.CategoryModel>>);

  @override
  _i8.Future<List<_i12.CategoryModel>> search(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
        ),
        returnValue:
            _i8.Future<List<_i12.CategoryModel>>.value(<_i12.CategoryModel>[]),
      ) as _i8.Future<List<_i12.CategoryModel>>);
}

/// A class which mocks [GetAllCategoriesUserCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllCategoriesUserCase extends _i1.Mock
    implements _i13.GetAllCategoriesUserCase {
  MockGetAllCategoriesUserCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.CategoryRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCategoryRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.CategoryRepository);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.CategoryEntity>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i8
            .Future<_i2.Either<_i9.Failure, List<_i10.CategoryEntity>>>.value(
            _FakeEither_0<_i9.Failure, List<_i10.CategoryEntity>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.CategoryEntity>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i10.CategoryEntity>>> search(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
        ),
        returnValue: _i8
            .Future<_i2.Either<_i9.Failure, List<_i10.CategoryEntity>>>.value(
            _FakeEither_0<_i9.Failure, List<_i10.CategoryEntity>>(
          this,
          Invocation.method(
            #search,
            [query],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i10.CategoryEntity>>>);
}

/// A class which mocks [PopularRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularRepository extends _i1.Mock implements _i4.PopularRepository {
  MockPopularRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i14.PopularEntity>>>
      getAllPopular() => (super.noSuchMethod(
            Invocation.method(
              #getAllPopular,
              [],
            ),
            returnValue: _i8.Future<
                    _i2.Either<_i9.Failure, List<_i14.PopularEntity>>>.value(
                _FakeEither_0<_i9.Failure, List<_i14.PopularEntity>>(
              this,
              Invocation.method(
                #getAllPopular,
                [],
              ),
            )),
          ) as _i8.Future<_i2.Either<_i9.Failure, List<_i14.PopularEntity>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i14.PopularEntity>>> search(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, List<_i14.PopularEntity>>>.value(
                _FakeEither_0<_i9.Failure, List<_i14.PopularEntity>>(
          this,
          Invocation.method(
            #search,
            [query],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i14.PopularEntity>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, bool>> toggleFavorite(
          _i14.PopularEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [entity],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, bool>>.value(
            _FakeEither_0<_i9.Failure, bool>(
          this,
          Invocation.method(
            #toggleFavorite,
            [entity],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, bool>>);
}

/// A class which mocks [PopularRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularRemoteDataSource extends _i1.Mock
    implements _i15.PopularRemoteDataSource {
  MockPopularRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i16.PopularModel>> getPopulars() => (super.noSuchMethod(
        Invocation.method(
          #getPopulars,
          [],
        ),
        returnValue:
            _i8.Future<List<_i16.PopularModel>>.value(<_i16.PopularModel>[]),
      ) as _i8.Future<List<_i16.PopularModel>>);

  @override
  _i8.Future<List<_i16.PopularModel>> search(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
        ),
        returnValue:
            _i8.Future<List<_i16.PopularModel>>.value(<_i16.PopularModel>[]),
      ) as _i8.Future<List<_i16.PopularModel>>);
}

/// A class which mocks [GetAllPopularUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllPopularUsecase extends _i1.Mock
    implements _i17.GetAllPopularUsecase {
  MockGetAllPopularUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.PopularRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePopularRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.PopularRepository);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i14.PopularEntity>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, List<_i14.PopularEntity>>>.value(
                _FakeEither_0<_i9.Failure, List<_i14.PopularEntity>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i14.PopularEntity>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, List<_i14.PopularEntity>>> search(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, List<_i14.PopularEntity>>>.value(
                _FakeEither_0<_i9.Failure, List<_i14.PopularEntity>>(
          this,
          Invocation.method(
            #search,
            [query],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, List<_i14.PopularEntity>>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, bool>> toggleFavorite(
          _i14.PopularEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleFavorite,
          [entity],
        ),
        returnValue: _i8.Future<_i2.Either<_i9.Failure, bool>>.value(
            _FakeEither_0<_i9.Failure, bool>(
          this,
          Invocation.method(
            #toggleFavorite,
            [entity],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, bool>>);
}

/// A class which mocks [TourRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTourRepository extends _i1.Mock implements _i6.TourRepository {
  MockTourRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Either<_i9.Failure, _i5.TourDetailEntity>> getTourDetail() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTourDetail,
          [],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, _i5.TourDetailEntity>>.value(
                _FakeEither_0<_i9.Failure, _i5.TourDetailEntity>(
          this,
          Invocation.method(
            #getTourDetail,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, _i5.TourDetailEntity>>);
}

/// A class which mocks [TourRemoteDetailDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTourRemoteDetailDataSource extends _i1.Mock
    implements _i18.TourRemoteDetailDataSource {
  MockTourRemoteDetailDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i5.TourDetailEntity> getTourDetail() => (super.noSuchMethod(
        Invocation.method(
          #getTourDetail,
          [],
        ),
        returnValue:
            _i8.Future<_i5.TourDetailEntity>.value(_FakeTourDetailEntity_3(
          this,
          Invocation.method(
            #getTourDetail,
            [],
          ),
        )),
      ) as _i8.Future<_i5.TourDetailEntity>);
}

/// A class which mocks [GetTourDetailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTourDetailUseCase extends _i1.Mock
    implements _i19.GetTourDetailUseCase {
  MockGetTourDetailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TourRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTourRepository_4(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i6.TourRepository);

  @override
  _i8.Future<_i2.Either<_i9.Failure, _i5.TourDetailEntity>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, _i5.TourDetailEntity>>.value(
                _FakeEither_0<_i9.Failure, _i5.TourDetailEntity>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, _i5.TourDetailEntity>>);
}

/// A class which mocks [HiveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveService extends _i1.Mock implements _i20.HiveService {
  MockHiveService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> openBox() => (super.noSuchMethod(
        Invocation.method(
          #openBox,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> closeBox() => (super.noSuchMethod(
        Invocation.method(
          #closeBox,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clearBox(String? boxName) => (super.noSuchMethod(
        Invocation.method(
          #clearBox,
          [boxName],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteBox(String? boxName) => (super.noSuchMethod(
        Invocation.method(
          #deleteBox,
          [boxName],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addData(
    String? boxName,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addData,
          [
            boxName,
            data,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getData(String? boxName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getData,
          [boxName],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<void> deleteData(
    String? boxName,
    int? index,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteData,
          [
            boxName,
            index,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [PopularLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularLocalDataSource extends _i1.Mock
    implements _i21.PopularLocalDataSource {
  MockPopularLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i16.PopularModel>> getSavedPopulars() => (super.noSuchMethod(
        Invocation.method(
          #getSavedPopulars,
          [],
        ),
        returnValue:
            _i8.Future<List<_i16.PopularModel>>.value(<_i16.PopularModel>[]),
      ) as _i8.Future<List<_i16.PopularModel>>);

  @override
  _i8.Future<List<_i16.PopularModel>> search(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
        ),
        returnValue:
            _i8.Future<List<_i16.PopularModel>>.value(<_i16.PopularModel>[]),
      ) as _i8.Future<List<_i16.PopularModel>>);

  @override
  _i8.Future<void> savePopular(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePopular,
          [data],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deletePopular(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deletePopular,
          [index],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i7.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i7.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i8.Future<_i7.Response>);

  @override
  _i8.Future<_i7.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i8.Future<_i7.Response>);

  @override
  _i8.Future<_i7.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i22.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i7.Response>);

  @override
  _i8.Future<_i7.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i22.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i7.Response>);

  @override
  _i8.Future<_i7.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i22.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i7.Response>);

  @override
  _i8.Future<_i7.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i22.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i8.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i8.Future<_i7.Response>);

  @override
  _i8.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<String>.value(_i23.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i24.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i8.Future<_i24.Uint8List>.value(_i24.Uint8List(0)),
      ) as _i8.Future<_i24.Uint8List>);

  @override
  _i8.Future<_i7.StreamedResponse> send(_i7.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i8.Future<_i7.StreamedResponse>.value(_FakeStreamedResponse_6(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i8.Future<_i7.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
